### ISSUE TITLE
Missing Data - Taxi Zone Lookup Table

### ISSUE THREAD

**Issue by SuchitSanghvi** [DataTalksClub/nyc-tlc-data#1]
Hi Alexey! Thanks for uploading the data. If you can also upload the taxi zone lookup table here, that would be great. 

https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv
or https://d37ci6vzurychx.cloudfront.net/misc/taxi+_zone_lookup.parquet

**Comment by alexeygrigorev** [comment]
Thanks! Here you go: https://github.com/DataTalksClub/nyc-tlc-data/releases/tag/misc
